# jaeger.yml - a docker-compose override that adds 'jaeger to the stack.
#
# once running, head to `localhost:25000` to get access to the Jaeger UI.
#
# ref: https://www.jaegertracing.io/
# ref: https://docs.docker.com/compose/extends/
#
volumes:
  elasticsearch-data:
services:
  web:
    environment:
      CONCOURSE_TRACING_SERVICE_NAME: atc
      CONCOURSE_TRACING_OTLP_ADDRESS: jaeger:4317
  worker:
    environment:
      CONCOURSE_TRACING_SERVICE_NAME: worker
      CONCOURSE_TRACING_OTLP_ADDRESS: jaeger:4317

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:latest
    restart: on-failure
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: :9411
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
      ES_TAGS_AS_FIELDS_ALL: "true"
      ES_NUM_REPLICAS: 0
    ports:
      - "25000:16686"
      - "9411:9411"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"

  elasticsearch:
    image: elasticsearch:7.17.28
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node

  kibana:
    image: kibana:7.17.28
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
