blank_issues_enabled: false

contact_links:
- name: ❔ Ask for help
  url: https://github.com/concourse/concourse/discussions/new?category=help-support
  about: Ask a question or troubleshoot a problem with Concourse.

- name: 💡 Discuss an idea
  url: https://github.com/concourse/concourse/discussions/new?category=ideas
  about: Discuss a workflow that Concourse could better support.
