jobs:
  - name: stream-logs
    plan:
      - task: logs
        config:
          platform: linux
          image_resource:
            type: mock
            source:
              mirror_self: true
          run:
            path: /bin/bash
            args:
              - -ec
              - |-
                for i in {1..120};  do
                  echo "Hello $i"
                  sleep 1
                done
