---
resources:
- name: mockery
  type: mock

jobs:
- name: serialized-by-active-tasks-limit
  plan:
  - get: mockery
  - in_parallel:
    - task: error
      config:
        platform: linux

        image_resource:
          type: mock
          source: {mirror_self: true}

        run:
          path: does-not-exist
          args: ["Hello, world!"]
    - task: failure
      config:
        platform: linux

        image_resource:
          type: mock
          source: {mirror_self: true}

        run:
          path: sh
          args: ["-c", "sleep 10; exit 1"]
    - task: success
      config:
        platform: linux

        image_resource:
          type: mock
          source: {mirror_self: true}

        run:
          path: sh
          args: ["-c", "sleep 10; exit 0"]
  - put: mockery
    params: {version: put-version}
